---
   environment: development
   chdir: /home/tad-dev/ruby/relogioDePonto
   address: 127.0.0.1
   port: 3000
   pid: /home/tad-dev/ruby/relogioDePonto/tmp/thin.pid
   rackup: /home/tad-dev/ruby/relogioDePonto/thin/config.ru
   log: /home/tad-dev/ruby/relogioDePonto/tmp/thin.log
   max_conns: 1024
   timeout: 30
   max_persistent_conns: 512
   daemonize: true
